name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build MenuMic.app
        run: |
          xcodebuild -project MenuMic.xcodeproj -scheme MenuMic -configuration Release -derivedDataPath build
      - name: Create DMG
        continue-on-error: true
        run: |
          npm install --global create-dmg
          create-dmg build/Build/Products/Release/MenuMic.app
      - name: Rename DMG
        run: |
          mv MenuMic*.dmg MenuMic.dmg
      - name: Upload to Tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MenuMic.dmg
          tag: ${{ github.ref }}
          overwrite: true
